FROM openjdk:17
ADD configuration-server-0.0.1-SNAPSHOT.jar configuration-server-0.0.1-SNAPSHOT.jar
EXPOSE 8071
ENTRYPOINT ["java", "-jar", "/configuration-server-0.0.1-SNAPSHOT.jar", "--spring.profiles.active=prod"]
